--4-1
select FO.POLICE as 轄管分局, PO.police_tel
 from FACILITY_INFO FO
 join POLICE_INFO PO
 on FO.POLICE = PO.POLICE
 where FO.PNUMBER > 1000;
--4-2
SELECT FACILITY_INFO.POLICE ,
police_info.police_tel, facility_info.shelter_ad,facility_info.building,
count(distinct facility_info.building) 
over(partition by facility_info.building) as s_number 
FROM FACILITY_INFO
JOIN POLICE_INFO
ON FACILITY_INFO.POLICE = POLICE_INFO.POLICE
WHERE FACILITY_INFO.PNUMBER > 1000;

--4-4
SELECT FACILITY_INFO.VILLAGE, FACILITY_INFO.SHELTER_AD, 
FACILITY_INFO.PNUMBER, FACILITY_INFO.POLICE,police_info.police_tel
FROM FACILITY_INFO
JOIN POLICE_INFO
ON FACILITY_INFO.POLICE = POLICE_INFO.POLICE
WHERE SHELTER_AD LIKE '%中%';

SELECT FACILITY_INFO.VILLAGE, FACILITY_INFO.SHELTER_AD, 
FACILITY_INFO.PNUMBER,village_info.village_ad
FROM FACILITY_INFO
JOIN VILLAGE_INFO
ON FACILITY_INFO.VILLAGE = village_info.village
WHERE BUILDING IN ('B01','B02');



