--4-1 
select distinct PO.POLICE_TEL,PO.PNAME
 from STUDENT.FACILITY_INFO FO
 left join POLICE_INFO PO 
 on FO.POLICE = PO.POLICE
 where FO.PNUMBER > 1000;
--4-2
select PO.PNAME ,
      PO.POLICE_TEL, FO.SHELTER_AD,
      FO.BNAME,
 count(FO.SHELTER_AD) 
 over(partition by FO.POLICE) as S_NUMBER 
 from STUDENT.FACILITY_INFO FO
 left join POLICE_INFO PO
 on FO.POLICE = PO.POLICE
 where FO.PNUMBER > 1000;
--4-4
select VO.VNAME, FO.SHELTER_AD, 
      FO.PNUMBER,PO.PNAME,PO.POLICE_TEL
 from STUDENT.FACILITY_INFO FO
 left join POLICE_INFO PO
 on FO.POLICE = PO.POLICE
 left join VILLAGE_INFO VO
 on FO.VILLAGE = VO.VILLAGE
 where SHELTER_AD like '%中%';
--4-5 
Select VO.VNAME, FO.SHELTER_AD, 
       FO.PNUMBER,VO.VILLAGE_AD
 from STUDENT.FACILITY_INFO FO
 left join VILLAGE_INFO VO
 on FO.VILLAGE = VO.VILLAGE
 where BNAME in ('公寓','大樓');

update FACILITY_INFO
set PNUMBER = 5000
where SHELTER_AD = '竹南鎮和平街79號'

delete from FACILITY_INFO
where PNUMBER <1000;



